/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VisualizationComponent {
        "data": string;
        "excludedProperties": string;
        "showAttributes": boolean;
        "showHover": boolean;
        "showPrimaryLinks": boolean;
        "size": string;
    }
}
declare global {
    interface HTMLVisualizationComponentElement extends Components.VisualizationComponent, HTMLStencilElement {
    }
    var HTMLVisualizationComponentElement: {
        prototype: HTMLVisualizationComponentElement;
        new (): HTMLVisualizationComponentElement;
    };
    interface HTMLElementTagNameMap {
        "visualization-component": HTMLVisualizationComponentElement;
    }
}
declare namespace LocalJSX {
    interface VisualizationComponent {
        "data"?: string;
        "excludedProperties"?: string;
        "showAttributes"?: boolean;
        "showHover"?: boolean;
        "showPrimaryLinks"?: boolean;
        "size"?: string;
    }
    interface IntrinsicElements {
        "visualization-component": VisualizationComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "visualization-component": LocalJSX.VisualizationComponent & JSXBase.HTMLAttributes<HTMLVisualizationComponentElement>;
        }
    }
}
