name: Deploy Storybook to GitHub Pages
on:
  release:
    types: [published]

jobs:
  build-component:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Build
        run: npm ci

  deploy-storybook:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Deploy Storybook to GitHub Pages
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.2
        with:
          path: storybook-static
          build_command: |
            npm run build
            npm run build-storybook
        
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  
          publish_dir: ./storybook-static 
