name: Deploy Storybook to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build-component:
    runs-on: ubuntu-latest
    environment:
        name: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: npm ci

  deploy-storybook:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Storybook to GitHub Pages
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.2
        with:
          path: storybook-static
          build_command: |
            npm run build
            npm run build-storybook
        
